name: Deploy Angular App to Azure
on:
  push:
    branches:
      - dev
env:
  AZURE_WEBAPP_NAME: My2CentsUI
  AZURE_WEBAPP_PACKAGE_PATH: './My-2-Cents-UI/dist/my-2-cents-ui'
  NODE_VERSION: '16.13.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: |
        cd My-2-Cents-UI/
        npm install
      
    - name: Build
      run: |
        cd My-2-Cents-UI/
        npm run build --if-present
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FOR_UI }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
